### ISSUE TITLE
Whitelisting Google domains

### ISSUE THREAD

**Issue by joshskinner** [waterlock/waterlock-google-auth#1]
Trying to figure out how I might whitelist certain Google domains within this module.

In my situation users have to login with Google so I believe they'd never have an authenticated session prior to entering the logic at: https://github.com/davidrivera/waterlock-google-auth/blob/master/lib/controllers/actions/oauth2.js#L32

I believe that since the 'attr' variable has the Google email address and is passed into engine.findOrCreateAuth with userFound as the callback, the waterlock engine method needs to cb('error') somehow.  

What I think would be nice to have is simply another block in the waterlock config right after my Google clientSecret called 'whitelistedDomains: ['domain1','domain2']

Thoughts?

**Comment by n3integration** [comment]
+1 - I would like to see similar behavior in the module. To take this a step further, I would like more fine grained control over the users that have access (i.e. the allow list could be an email address or a domain).
